import Head from "next/head";
import Link from "next/link";

import styles from "../styles/Home.module.css";
import CloseSharpIcon from "@mui/icons-material/CloseSharp";
import GridViewSharpIcon from "@mui/icons-material/GridViewSharp";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>My title</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<body>
				<h1>Home</h1>
			</body>
		</div>
	);
}
